"""Cascade relay module.

Provides config-backed list / status / apply primitives plus diagnostics
rendering for the CLI and web panel.

Apply generates two artifacts under *artifacts_dir*:
  - ``cascade/3proxy.cfg``  — 3proxy chain config (SOCKS5 → upstream SOCKS)
  - ``cascade/cascade.service`` — systemd unit
  - ``cascade/state.json`` — applied config snapshot

Rule management writes to:
  - ``cascade/rules.json`` — list of managed rules (persisted across sessions)
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from pathlib import Path

from rich.panel import Panel
from rich.table import Table

from daran_proxy_stack.lib.models import CascadeConfig
from daran_proxy_stack.lib.shell import run


# ---------------------------------------------------------------------------
# Diagnostics (existing, retained)
# ---------------------------------------------------------------------------

@dataclass
class CascadeDiagnostics:
    note: str = "cascade module not yet implemented"
    config_present: bool = False
    relay_reachable: bool = False
    upstream_reachable: bool = False


def _port_open(host: str, port: int) -> bool:
    result = run(["bash", "-lc", f"timeout 1 bash -c 'echo >/dev/tcp/{host}/{port}' 2>/dev/null && echo ok || echo fail"])
    return result.ok and "ok" in (result.stdout or "")


def collect_diagnostics(config: CascadeConfig | None = None) -> CascadeDiagnostics:
    if config is None:
        return CascadeDiagnostics()

    relay_reachable = _port_open(config.relay_host, config.relay_port) if config.enabled else False
    upstream_reachable = _port_open(config.upstream_socks_host, config.upstream_socks_port) if config.enabled else False

    return CascadeDiagnostics(
        note="enabled — checking connectivity" if config.enabled else "disabled in config",
        config_present=True,
        relay_reachable=relay_reachable,
        upstream_reachable=upstream_reachable,
    )


def render_summary(config: CascadeConfig, diagnostics: CascadeDiagnostics | None = None) -> Panel:
    table = Table.grid(padding=(0, 2))
    table.add_row("Mode", config.mode)
    table.add_row("Relay", f"{config.relay_host}:{config.relay_port}")
    table.add_row("Upstream SOCKS", f"{config.upstream_socks_host}:{config.upstream_socks_port}")
    table.add_row("Enabled", "yes" if config.enabled else "no")
    if diagnostics is not None:
        table.add_row("Status", diagnostics.note)
        table.add_row("Relay reachable", "yes" if diagnostics.relay_reachable else "no")
        table.add_row("Upstream reachable", "yes" if diagnostics.upstream_reachable else "no")
    else:
        table.add_row("Status", "not checked")
    return Panel(table, title="Cascade module", border_style="yellow")


# ---------------------------------------------------------------------------
# Config-backed primitives (new)
# ---------------------------------------------------------------------------

def list_relays(config: CascadeConfig) -> list[dict]:
    """Return the configured relay entries as a list of dicts.

    Currently the config holds a single relay; returns a one-item list so
    the API response is already collection-shaped for future expansion.
    """
    return [
        {
            "id": "relay-0",
            "relay": f"{config.relay_host}:{config.relay_port}",
            "upstream_socks": f"{config.upstream_socks_host}:{config.upstream_socks_port}",
            "mode": config.mode,
            "enabled": config.enabled,
        }
    ]


def status_dict(config: CascadeConfig) -> dict:
    """Return a JSON-serialisable status snapshot (runs TCP probes)."""
    diag = collect_diagnostics(config)
    return {
        "enabled": config.enabled,
        "relay": f"{config.relay_host}:{config.relay_port}",
        "upstream_socks": f"{config.upstream_socks_host}:{config.upstream_socks_port}",
        "relay_reachable": diag.relay_reachable,
        "upstream_reachable": diag.upstream_reachable,
        "note": diag.note,
    }


def render_rules_section(rules: list[dict]) -> str:
    """Render 3proxy tcppm/udppm entries for managed rules.

    Each rule maps to one or two port-mapper lines:
      tcp  → tcppm -p<listen_port> -i0.0.0.0 -e<target_host> -E<target_port>
      udp  → udppm -p<listen_port> -i0.0.0.0 -e<target_host> -E<target_port>
      both → both tcppm and udppm lines

    Returns empty string when rules list is empty.
    """
    if not rules:
        return ""

    lines: list[str] = [
        "# Managed rules — generated by daran-proxy-stack",
    ]
    for r in rules:
        protocol = r.get("protocol", "tcp")
        listen_port = r["listen_port"]
        target_host = r["target_host"]
        target_port = r["target_port"]
        notes = r.get("notes", "")
        comment = f"  # {notes}" if notes else ""
        if protocol in ("tcp", "both"):
            lines.append(
                f"tcppm -p{listen_port} -i0.0.0.0 -e{target_host} -E{target_port}{comment}"
            )
        if protocol in ("udp", "both"):
            lines.append(
                f"udppm -p{listen_port} -i0.0.0.0 -e{target_host} -E{target_port}{comment}"
            )
    return "\n".join(lines) + "\n"


def render_3proxy_config(config: CascadeConfig, rules: list[dict] | None = None) -> str:
    """Render a 3proxy config that listens as SOCKS5 and chains to upstream.

    When ``rules`` is provided and non-empty, tcppm/udppm entries are appended
    for each managed rule.
    """
    parts = [
        "# Generated by daran-proxy-stack — cascade relay\n"
        "nscache 65536\n"
        "timeouts 1 5 30 60 180 1800 15 60\n"
        "\n"
        f"parent 1000 socks5 {config.upstream_socks_host} {config.upstream_socks_port}\n"
        "\n"
        f"socks -p {config.relay_port} -i {config.relay_host}\n"
    ]
    if rules:
        rules_text = render_rules_section(rules)
        if rules_text:
            parts.append("\n" + rules_text)
    return "".join(parts)


def render_systemd_unit(config: CascadeConfig) -> str:
    """Render a systemd unit that runs 3proxy with the generated config."""
    cfg_path = "/etc/daran-proxy-stack/cascade/3proxy.cfg"
    return (
        "[Unit]\n"
        "Description=daran-proxy-stack cascade relay (3proxy)\n"
        "After=network.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart=/usr/bin/3proxy {cfg_path}\n"
        "Restart=on-failure\n"
        "RestartSec=5s\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def apply(config: CascadeConfig, artifacts_dir: Path) -> str:
    """Write cascade config artifacts; return a human-readable summary.

    Loads managed rules from ``rules.json`` (if present) and embeds them into
    the generated ``3proxy.cfg`` as tcppm/udppm port-mapper entries.

    Does NOT start any process — callers or the operator do that.
    Returns a multiline string suitable for task.output.
    """
    out_dir = artifacts_dir / "cascade"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load managed rules so they feed directly into the generated config
    rules = load_rules(artifacts_dir)

    cfg_text = render_3proxy_config(config, rules=rules)
    svc_text = render_systemd_unit(config)
    state = {
        "relay_host": config.relay_host,
        "relay_port": config.relay_port,
        "upstream_socks_host": config.upstream_socks_host,
        "upstream_socks_port": config.upstream_socks_port,
        "mode": config.mode,
        "enabled": config.enabled,
        "rules_count": len(rules),
    }

    (out_dir / "3proxy.cfg").write_text(cfg_text, encoding="utf-8")
    (out_dir / "cascade.service").write_text(svc_text, encoding="utf-8")
    (out_dir / "state.json").write_text(json.dumps(state, indent=2), encoding="utf-8")

    lines = [
        f"wrote {out_dir / '3proxy.cfg'}",
        f"wrote {out_dir / 'cascade.service'}",
        f"wrote {out_dir / 'state.json'}",
        f"relay  : {config.relay_host}:{config.relay_port}",
        f"upstream: {config.upstream_socks_host}:{config.upstream_socks_port}",
        f"rules  : {len(rules)} managed rule(s) embedded",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rule management (managed rules stored in rules.json)
# ---------------------------------------------------------------------------

def _rules_path(artifacts_dir: Path) -> Path:
    return artifacts_dir / "cascade" / "rules.json"


def load_rules(artifacts_dir: Path) -> list[dict]:
    """Load managed rules from rules.json. Returns [] if file absent/malformed."""
    p = _rules_path(artifacts_dir)
    if not p.exists():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except Exception:
        return []


def save_rules(artifacts_dir: Path, rules: list[dict]) -> None:
    """Write rules list to rules.json, creating parent dirs as needed."""
    p = _rules_path(artifacts_dir)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(rules, indent=2), encoding="utf-8")


def add_rule(
    artifacts_dir: Path,
    *,
    protocol: str,
    listen_port: int,
    target_host: str,
    target_port: int,
    notes: str = "",
) -> dict:
    """Add a new managed rule to rules.json. Returns the created rule dict."""
    rules = load_rules(artifacts_dir)
    rule: dict = {
        "id": f"rule-managed-{uuid.uuid4().hex[:8]}",
        "protocol": protocol,
        "listen_port": listen_port,
        "target_host": target_host,
        "target_port": target_port,
        "status": "managed",
        "notes": notes,
    }
    rules.append(rule)
    save_rules(artifacts_dir, rules)
    return rule


def remove_rule(artifacts_dir: Path, rule_id: str) -> bool:
    """Remove rule by id from rules.json. Returns True if found and removed."""
    rules = load_rules(artifacts_dir)
    before = len(rules)
    rules = [r for r in rules if r.get("id") != rule_id]
    if len(rules) == before:
        return False
    save_rules(artifacts_dir, rules)
    return True


def reset_rules(artifacts_dir: Path) -> int:
    """Clear all managed rules from rules.json. Returns count of removed rules."""
    rules = load_rules(artifacts_dir)
    count = len(rules)
    save_rules(artifacts_dir, [])
    return count


# ---------------------------------------------------------------------------
# IPTables relay (raw port forwarding: RU VPS → FI VPS)
# ---------------------------------------------------------------------------

def check_ip_forward() -> bool:
    """Return True if IPv4 forwarding is currently enabled."""
    try:
        return Path("/proc/sys/net/ipv4/ip_forward").read_text(encoding="utf-8").strip() == "1"
    except Exception:
        return False


def generate_relay_iptables_commands(target_host: str, rules: list[dict]) -> list[str]:
    """Build sysctl + iptables DNAT + MASQUERADE commands for relay setup.

    Each rule dict: {protocol: tcp|udp|both, listen_port: int, target_port: int}.
    Returns shell command strings for ``run(["sudo", "sh", "-c", cmd])``.
    """
    cmds: list[str] = [
        "sysctl -w net.ipv4.ip_forward=1",
        "grep -qxF 'net.ipv4.ip_forward=1' /etc/sysctl.conf "
        "|| echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf",
    ]
    for r in rules:
        proto = r.get("protocol", "tcp")
        lport = r["listen_port"]
        tport = r.get("target_port", lport)
        protos = ["tcp", "udp"] if proto == "both" else [proto]
        for p in protos:
            cmds.append(
                f"iptables -t nat -A PREROUTING -p {p} --dport {lport} "
                f"-j DNAT --to-destination {target_host}:{tport}"
            )
    cmds.append("iptables -t nat -A POSTROUTING -j MASQUERADE")
    return cmds


def generate_relay_flush_commands(target_host: str, rules: list[dict]) -> list[str]:
    """Build iptables delete commands to undo a relay setup."""
    cmds: list[str] = []
    for r in rules:
        proto = r.get("protocol", "tcp")
        lport = r["listen_port"]
        tport = r.get("target_port", lport)
        protos = ["tcp", "udp"] if proto == "both" else [proto]
        for p in protos:
            cmds.append(
                f"iptables -t nat -D PREROUTING -p {p} --dport {lport} "
                f"-j DNAT --to-destination {target_host}:{tport} 2>/dev/null || true"
            )
    return cmds


def render_relay_script(target_host: str, rules: list[dict]) -> str:
    """Render a self-contained bash script that applies the relay rules."""
    cmds = generate_relay_iptables_commands(target_host, rules)
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by daran-proxy-stack — iptables relay",
        f"# Target host: {target_host}",
        "# Run as root or with sudo.",
        "set -euo pipefail",
        "",
    ]
    lines.extend(cmds)
    lines += [
        "",
        "# Persist rules so they survive reboots",
        "if command -v netfilter-persistent &>/dev/null; then",
        "    netfilter-persistent save",
        "elif command -v iptables-save &>/dev/null; then",
        "    mkdir -p /etc/iptables",
        "    iptables-save > /etc/iptables/rules.v4",
        "fi",
        "",
        "echo 'Relay rules applied successfully.'",
    ]
    return "\n".join(lines) + "\n"


def apply_iptables_relay(target_host: str, rules: list[dict]) -> tuple[bool, str]:
    """Execute relay iptables commands via sudo. Returns (ok, message)."""
    cmds = generate_relay_iptables_commands(target_host, rules)
    errors: list[str] = []
    applied = 0
    for cmd in cmds:
        r = run(["sudo", "sh", "-c", cmd])
        if r.ok:
            applied += 1
        else:
            errors.append(f"  [{cmd}] → {(r.stderr or r.stdout or '').strip()}")
    if errors:
        return False, f"Применено {applied}/{len(cmds)}, ошибки:\n" + "\n".join(errors)
    return True, f"Применено команд: {applied}."


def flush_iptables_relay(target_host: str, rules: list[dict]) -> tuple[bool, str]:
    """Execute iptables delete commands via sudo. Returns (ok, message)."""
    cmds = generate_relay_flush_commands(target_host, rules)
    errors: list[str] = []
    for cmd in cmds:
        r = run(["sudo", "sh", "-c", cmd])
        if not r.ok and "No chain" not in (r.stderr or ""):
            errors.append(f"  {(r.stderr or r.stdout or '').strip()}")
    if errors:
        return False, "Ошибки при удалении:\n" + "\n".join(errors)
    return True, f"Удалено правил: {len(cmds)}."


def save_relay_state(artifacts_dir: Path, target_host: str, rules: list[dict]) -> None:
    """Persist relay config to relay-state.json."""
    out = artifacts_dir / "cascade" / "relay-state.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps({"target_host": target_host, "rules": rules}, indent=2),
        encoding="utf-8",
    )


def load_relay_state(artifacts_dir: Path) -> dict | None:
    """Load saved relay state. Returns None if absent or malformed."""
    p = artifacts_dir / "cascade" / "relay-state.json"
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except Exception:
        return None
