"""Cascade relay module.

Provides config-backed list / status / apply primitives plus diagnostics
rendering for the CLI and web panel.

Apply generates two artifacts under *artifacts_dir*:
  - ``cascade/3proxy.cfg``  — 3proxy chain config (SOCKS5 → upstream SOCKS)
  - ``cascade/cascade.service`` — systemd unit
  - ``cascade/state.json`` — applied config snapshot

Rule management writes to:
  - ``cascade/rules.json`` — list of managed rules (persisted across sessions)
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from pathlib import Path

from rich.panel import Panel
from rich.table import Table

from daran_proxy_stack.lib.models import CascadeConfig
from daran_proxy_stack.lib.shell import run


# ---------------------------------------------------------------------------
# Diagnostics (existing, retained)
# ---------------------------------------------------------------------------

@dataclass
class CascadeDiagnostics:
    note: str = "cascade module not yet implemented"
    config_present: bool = False
    relay_reachable: bool = False
    upstream_reachable: bool = False


def _port_open(host: str, port: int) -> bool:
    result = run(["bash", "-lc", f"timeout 1 bash -c 'echo >/dev/tcp/{host}/{port}' 2>/dev/null && echo ok || echo fail"])
    return result.ok and "ok" in (result.stdout or "")


def collect_diagnostics(config: CascadeConfig | None = None) -> CascadeDiagnostics:
    if config is None:
        return CascadeDiagnostics()

    relay_reachable = _port_open(config.relay_host, config.relay_port) if config.enabled else False
    upstream_reachable = _port_open(config.upstream_socks_host, config.upstream_socks_port) if config.enabled else False

    return CascadeDiagnostics(
        note="enabled — checking connectivity" if config.enabled else "disabled in config",
        config_present=True,
        relay_reachable=relay_reachable,
        upstream_reachable=upstream_reachable,
    )


def render_summary(config: CascadeConfig, diagnostics: CascadeDiagnostics | None = None) -> Panel:
    table = Table.grid(padding=(0, 2))
    table.add_row("Mode", config.mode)
    table.add_row("Relay", f"{config.relay_host}:{config.relay_port}")
    table.add_row("Upstream SOCKS", f"{config.upstream_socks_host}:{config.upstream_socks_port}")
    table.add_row("Enabled", "yes" if config.enabled else "no")
    if diagnostics is not None:
        table.add_row("Status", diagnostics.note)
        table.add_row("Relay reachable", "yes" if diagnostics.relay_reachable else "no")
        table.add_row("Upstream reachable", "yes" if diagnostics.upstream_reachable else "no")
    else:
        table.add_row("Status", "not checked")
    return Panel(table, title="Cascade module", border_style="yellow")


# ---------------------------------------------------------------------------
# Config-backed primitives (new)
# ---------------------------------------------------------------------------

def list_relays(config: CascadeConfig) -> list[dict]:
    """Return the configured relay entries as a list of dicts.

    Currently the config holds a single relay; returns a one-item list so
    the API response is already collection-shaped for future expansion.
    """
    return [
        {
            "id": "relay-0",
            "relay": f"{config.relay_host}:{config.relay_port}",
            "upstream_socks": f"{config.upstream_socks_host}:{config.upstream_socks_port}",
            "mode": config.mode,
            "enabled": config.enabled,
        }
    ]


def status_dict(config: CascadeConfig) -> dict:
    """Return a JSON-serialisable status snapshot (runs TCP probes)."""
    diag = collect_diagnostics(config)
    return {
        "enabled": config.enabled,
        "relay": f"{config.relay_host}:{config.relay_port}",
        "upstream_socks": f"{config.upstream_socks_host}:{config.upstream_socks_port}",
        "relay_reachable": diag.relay_reachable,
        "upstream_reachable": diag.upstream_reachable,
        "note": diag.note,
    }


def render_3proxy_config(config: CascadeConfig) -> str:
    """Render a 3proxy config that listens as SOCKS5 and chains to upstream."""
    return (
        "# Generated by daran-proxy-stack — cascade relay\n"
        "nscache 65536\n"
        "timeouts 1 5 30 60 180 1800 15 60\n"
        "\n"
        f"parent 1000 socks5 {config.upstream_socks_host} {config.upstream_socks_port}\n"
        "\n"
        f"socks -p {config.relay_port} -i {config.relay_host}\n"
    )


def render_systemd_unit(config: CascadeConfig) -> str:
    """Render a systemd unit that runs 3proxy with the generated config."""
    cfg_path = "/etc/daran-proxy-stack/cascade/3proxy.cfg"
    return (
        "[Unit]\n"
        "Description=daran-proxy-stack cascade relay (3proxy)\n"
        "After=network.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"ExecStart=/usr/bin/3proxy {cfg_path}\n"
        "Restart=on-failure\n"
        "RestartSec=5s\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def apply(config: CascadeConfig, artifacts_dir: Path) -> str:
    """Write cascade config artifacts; return a human-readable summary.

    Does NOT start any process — callers or the operator do that.
    Returns a multiline string suitable for task.output.
    """
    out_dir = artifacts_dir / "cascade"
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg_text = render_3proxy_config(config)
    svc_text = render_systemd_unit(config)
    state = {
        "relay_host": config.relay_host,
        "relay_port": config.relay_port,
        "upstream_socks_host": config.upstream_socks_host,
        "upstream_socks_port": config.upstream_socks_port,
        "mode": config.mode,
        "enabled": config.enabled,
    }

    (out_dir / "3proxy.cfg").write_text(cfg_text, encoding="utf-8")
    (out_dir / "cascade.service").write_text(svc_text, encoding="utf-8")
    (out_dir / "state.json").write_text(json.dumps(state, indent=2), encoding="utf-8")

    lines = [
        f"wrote {out_dir / '3proxy.cfg'}",
        f"wrote {out_dir / 'cascade.service'}",
        f"wrote {out_dir / 'state.json'}",
        f"relay  : {config.relay_host}:{config.relay_port}",
        f"upstream: {config.upstream_socks_host}:{config.upstream_socks_port}",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rule management (managed rules stored in rules.json)
# ---------------------------------------------------------------------------

def _rules_path(artifacts_dir: Path) -> Path:
    return artifacts_dir / "cascade" / "rules.json"


def load_rules(artifacts_dir: Path) -> list[dict]:
    """Load managed rules from rules.json. Returns [] if file absent/malformed."""
    p = _rules_path(artifacts_dir)
    if not p.exists():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except Exception:
        return []


def save_rules(artifacts_dir: Path, rules: list[dict]) -> None:
    """Write rules list to rules.json, creating parent dirs as needed."""
    p = _rules_path(artifacts_dir)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(rules, indent=2), encoding="utf-8")


def add_rule(
    artifacts_dir: Path,
    *,
    protocol: str,
    listen_port: int,
    target_host: str,
    target_port: int,
    notes: str = "",
) -> dict:
    """Add a new managed rule to rules.json. Returns the created rule dict."""
    rules = load_rules(artifacts_dir)
    rule: dict = {
        "id": f"rule-managed-{uuid.uuid4().hex[:8]}",
        "protocol": protocol,
        "listen_port": listen_port,
        "target_host": target_host,
        "target_port": target_port,
        "status": "managed",
        "notes": notes,
    }
    rules.append(rule)
    save_rules(artifacts_dir, rules)
    return rule


def remove_rule(artifacts_dir: Path, rule_id: str) -> bool:
    """Remove rule by id from rules.json. Returns True if found and removed."""
    rules = load_rules(artifacts_dir)
    before = len(rules)
    rules = [r for r in rules if r.get("id") != rule_id]
    if len(rules) == before:
        return False
    save_rules(artifacts_dir, rules)
    return True


def reset_rules(artifacts_dir: Path) -> int:
    """Clear all managed rules from rules.json. Returns count of removed rules."""
    rules = load_rules(artifacts_dir)
    count = len(rules)
    save_rules(artifacts_dir, [])
    return count
